<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Putri Pradevi">

<title>Analisis Regresi FDR Triwulan 3 Tahun 2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Regresi FDR Triwulan 3 2022_files/libs/clipboard/clipboard.min.js"></script>
<script src="Regresi FDR Triwulan 3 2022_files/libs/quarto-html/quarto.js"></script>
<script src="Regresi FDR Triwulan 3 2022_files/libs/quarto-html/popper.min.js"></script>
<script src="Regresi FDR Triwulan 3 2022_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Regresi FDR Triwulan 3 2022_files/libs/quarto-html/anchor.min.js"></script>
<link href="Regresi FDR Triwulan 3 2022_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Regresi FDR Triwulan 3 2022_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Regresi FDR Triwulan 3 2022_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Regresi FDR Triwulan 3 2022_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Regresi FDR Triwulan 3 2022_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analisis Regresi FDR Triwulan 3 Tahun 2022</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Putri Pradevi </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="analisis-regresi-linear-berganda-financial-data-and-ratio-triwulan-3-tahun-2022" class="level1">
<h1>ANALISIS REGRESI LINEAR BERGANDA FINANCIAL DATA AND RATIO TRIWULAN 3 TAHUN 2022</h1>
<p>Berikut ini langkah-langkah untuk melakukan regresi linear berganda dengan menggunakan dataset Financial Data and Ratio Q3 2022. Regresi ini digunakan untuk menguji variabel Harga Saham sebagai variabel dependen dan Profit, EPS, dan BVE sebagai variabel independen.</p>
<section id="memuat-packages-yang-digunakan" class="level2">
<h2 class="anchored" data-anchor-id="memuat-packages-yang-digunakan">1. Memuat Packages yang Digunakan</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Project UAS Data Analitik"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tibble' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'stringr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'forcats' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lmtest' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: zoo</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'zoo' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'zoo'

The following objects are masked from 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'car' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'carData' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'

The following object is masked from 'package:dplyr':

    recode

The following object is masked from 'package:purrr':

    some</code></pre>
</div>
</div>
</section>
<section id="akses-datamemuat-data" class="level2">
<h2 class="anchored" data-anchor-id="akses-datamemuat-data">2. Akses Data/Memuat Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readxl' was built under R version 4.3.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>Financial_Data_Ratio_Q3_2022 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"Financial Data &amp; Ratio - Q3 2022.xlsx"</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(Financial_Data_Ratio_Q3_2022)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="penyiapan-datadata-preparation" class="level2">
<h2 class="anchored" data-anchor-id="penyiapan-datadata-preparation">3. Penyiapan Data/Data Preparation</h2>
<section id="mengubah-nama-kolom-dataset" class="level3">
<h3 class="anchored" data-anchor-id="mengubah-nama-kolom-dataset">Mengubah nama kolom dataset</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>fdr <span class="ot">&lt;-</span> Financial_Data_Ratio_Q3_2022</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(fdr)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(fdr) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Sektor"</span>, <span class="st">"Kode Sub Industri"</span>, <span class="st">"Sub Industri"</span>, <span class="st">"Kode"</span>, <span class="st">"Nama Emiten"</span>, <span class="st">"Syariah"</span>, <span class="st">"Tanggal LK"</span>, <span class="st">"Tahun Fiskal"</span>, <span class="st">"Jenis Laporan Keuangan"</span>, <span class="st">"Opini Auditor"</span>, <span class="st">"Aset"</span>, <span class="st">"Liabilitas"</span>, <span class="st">"Ekuitas"</span>, <span class="st">"Pendapatan"</span>, <span class="st">"EBT"</span>, <span class="st">"Profit"</span>, <span class="st">"POA"</span>, <span class="st">"EPS"</span>, <span class="st">"BVE"</span>, <span class="st">"PER"</span>, <span class="st">"PBV"</span>, <span class="st">"DER"</span>, <span class="st">"ROA"</span>, <span class="st">"ROE"</span>, <span class="st">"NPM"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="membuat-dataset-baru-dari-aset-sampai-dengan-npm" class="level3">
<h3 class="anchored" data-anchor-id="membuat-dataset-baru-dari-aset-sampai-dengan-npm">Membuat Dataset Baru dari Aset sampai dengan NPM</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>FDR <span class="ot">&lt;-</span> fdr<span class="sc">%&gt;%</span><span class="fu">select</span>(Aset, Liabilitas, Ekuitas, Pendapatan, EBT, Profit, POA, EPS, BVE, PER, PBV, DER, ROA, ROE, NPM)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(FDR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="mengubah-data-karakter-menjadi-numerik" class="level3">
<h3 class="anchored" data-anchor-id="mengubah-data-karakter-menjadi-numerik">Mengubah Data Karakter menjadi Numerik</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>FDR <span class="ot">&lt;-</span> FDR<span class="sc">%&gt;%</span><span class="fu">mutate_if</span>(is.character, as.numeric)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There were 15 warnings in `mutate()`.
The first warning was:
ℹ In argument: `Aset = .Primitive("as.double")(Aset)`.
Caused by warning:
! NAs introduced by coercion
ℹ Run `dplyr::last_dplyr_warnings()` to see the 14 remaining warnings.</code></pre>
</div>
</div>
</section>
<section id="menampilkan-data" class="level3">
<h3 class="anchored" data-anchor-id="menampilkan-data">Menampilkan Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(FDR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 812
Columns: 15
$ Aset       &lt;dbl&gt; 16960.16, 130793.60, 34.62, 27834.66, 5279.11, 5263.50, 637…
$ Liabilitas &lt;dbl&gt; 10885.54, 48844.18, 16.73, 15843.10, 3295.42, 4411.02, 741.…
$ Ekuitas    &lt;dbl&gt; 6074.62, 81949.41, 17.88, 11991.55, 1983.69, 852.47, -104.4…
$ Pendapatan &lt;dbl&gt; 6483.46, 52702.34, 20.46, 22109.45, 695.50, 1371.76, 1.52, …
$ EBT        &lt;dbl&gt; 3926.35, 30378.02, 2.49, 1175.72, 44.06, 296.49, -6.55, -2.…
$ Profit     &lt;dbl&gt; 3037.55, 20022.27, 2.49, 927.41, 31.95, 254.57, -6.04, -3.1…
$ POA        &lt;dbl&gt; 3006.19, 18046.78, 2.49, 955.46, 31.95, 219.20, -5.99, -3.1…
$ EPS        &lt;dbl&gt; 115.51, 563.32, 20.90, 75.56, 20.53, 15.05, -14.02, 0.58, 2…
$ BVE        &lt;dbl&gt; 148.59, 2562.04, 81.28, 597.38, 709.27, 272.27, -13.32, 43.…
$ PER        &lt;dbl&gt; 15.80, 6.28, 11.87, 17.80, 17.92, 14.36, -3.57, 85.90, 9.36…
$ PBV        &lt;dbl&gt; 12.11, 1.38, 2.98, 2.26, 0.49, 0.79, -3.75, 1.14, 1.47, 1.4…
$ DER        &lt;dbl&gt; 1.79, 0.60, 0.94, 1.32, 1.66, 5.17, -7.10, 0.44, 0.57, 1.34…
$ ROA        &lt;dbl&gt; 28, 22, 13, 5, 1, 4, -17, 1, 10, 1, -13, 4, 68, -46, 7, 72,…
$ ROE        &lt;dbl&gt; 78, 35, 26, 13, 3, 28, NA, 1, 16, 2, NA, 10, 94, -222, 37, …
$ NPM        &lt;dbl&gt; 73, 55, 22, 7, 8, 17, -7227, 8, 35, 65, -45, 9, 67, -832, 3…</code></pre>
</div>
</div>
</section>
<section id="membuat-variabel-price" class="level3">
<h3 class="anchored" data-anchor-id="membuat-variabel-price">Membuat Variabel Price</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>FDR <span class="ot">&lt;-</span> FDR<span class="sc">%&gt;%</span><span class="fu">mutate</span>(<span class="st">"Harga Saham"</span> <span class="ot">=</span> PER<span class="sc">*</span>EPS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="mengganti-nilai-na-dengan-0-dalam-dataset" class="level3">
<h3 class="anchored" data-anchor-id="mengganti-nilai-na-dengan-0-dalam-dataset">Mengganti nilai NA dengan 0 dalam dataset</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>FDR[<span class="fu">is.na</span>(FDR)] <span class="ot">&lt;-</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="visualisasi-data-dan-pengujian-korelasi" class="level2">
<h2 class="anchored" data-anchor-id="visualisasi-data-dan-pengujian-korelasi">4. Visualisasi Data dan Pengujian Korelasi</h2>
<section id="visualisasi-data-menggunakan-scatterplot" class="level3">
<h3 class="anchored" data-anchor-id="visualisasi-data-menggunakan-scatterplot">Visualisasi Data menggunakan Scatterplot</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(FDR, <span class="fu">aes</span>(Profit, <span class="st">`</span><span class="at">Harga Saham</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"green"</span>) <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Regresi-FDR-Triwulan-3-2022_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(FDR, <span class="fu">aes</span>(EPS, <span class="st">`</span><span class="at">Harga Saham</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Regresi-FDR-Triwulan-3-2022_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(FDR, <span class="fu">aes</span>(BVE, <span class="st">`</span><span class="at">Harga Saham</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Regresi-FDR-Triwulan-3-2022_files/figure-html/unnamed-chunk-9-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="visualisasi-data-menggunakan-scatterplot-untuk-1-variabel-dependen-dan-3-variabel-independen" class="level3">
<h3 class="anchored" data-anchor-id="visualisasi-data-menggunakan-scatterplot-untuk-1-variabel-dependen-dan-3-variabel-independen">Visualisasi Data menggunakan Scatterplot untuk 1 Variabel Dependen dan 3 Variabel Independen</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(FDR, <span class="fu">aes</span>(<span class="at">y =</span> <span class="st">`</span><span class="at">Harga Saham</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> Profit, <span class="at">color =</span> <span class="st">"Profit"</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> EPS, <span class="at">color =</span> <span class="st">"EPS"</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> BVE, <span class="at">color =</span> <span class="st">"BVE"</span>)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatterplot Variabel Independen terhadap Variabel Harga Saham"</span>, <span class="at">y =</span> <span class="st">"Harga Saham"</span>, <span class="at">x =</span> <span class="st">"Nilai Variabel Independen"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Regresi-FDR-Triwulan-3-2022_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="pengujian-korelasi" class="level3">
<h3 class="anchored" data-anchor-id="pengujian-korelasi">Pengujian Korelasi</h3>
<section id="a.-uji-korelasi-hubungan-antara-variabel-harga-saham-dengan-profit" class="level4">
<h4 class="anchored" data-anchor-id="a.-uji-korelasi-hubungan-antara-variabel-harga-saham-dengan-profit">a. Uji Korelasi Hubungan antara Variabel Harga Saham dengan Profit</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(FDR<span class="sc">$</span>Profit, FDR<span class="sc">$</span><span class="st">`</span><span class="at">Harga Saham</span><span class="st">`</span>, <span class="at">method =</span> <span class="st">"pearson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  FDR$Profit and FDR$`Harga Saham`
t = 11.58, df = 810, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.3162762 0.4344113
sample estimates:
      cor 
0.3768753 </code></pre>
</div>
</div>
<p>Berdasarkan uji korelasi hubungan antara variabel Harga Saham dan Profit menunjukkan bahwa terdapat hubungan positif yang signifikan antara Profit dan Harga Saham. Meskipun hubungan tersebut signifikan, nilai korelasinya masih tergolong rendah (0.3768753). Keberadaan hubungan positif menunjukkan bahwa ketika Profit meningkat, kemungkinan Harga Saham juga cenderung meningkat, dan sebaliknya.</p>
</section>
<section id="b.-uji-korelasi-hubungan-antara-variabel-harga-saham-dengan-eps" class="level4">
<h4 class="anchored" data-anchor-id="b.-uji-korelasi-hubungan-antara-variabel-harga-saham-dengan-eps">b. Uji Korelasi Hubungan antara Variabel Harga Saham dengan EPS</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(FDR<span class="sc">$</span>EPS, FDR<span class="sc">$</span><span class="st">`</span><span class="at">Harga Saham</span><span class="st">`</span>, <span class="at">method =</span> <span class="st">"pearson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  FDR$EPS and FDR$`Harga Saham`
t = 15.497, df = 810, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.4233369 0.5295848
sample estimates:
      cor 
0.4782087 </code></pre>
</div>
</div>
<p>Berdasarkan uji korelasi bungan antara variabel Harga Saham dan EPS menunjukkan bahwa terdapat hubungan positif yang signifikan dan kuat antara EPS dan Harga Saham. Nilai korelasi yang tergolong cukup kuat (0.4782087) menunjukkan bahwa perubahan dalam EPS cenderung berkorelasi dengan perubahan dalam Harga Saham.</p>
</section>
<section id="c.-uji-korelasi-hubungan-antara-variabel-harga-saham-dengan-bve" class="level4">
<h4 class="anchored" data-anchor-id="c.-uji-korelasi-hubungan-antara-variabel-harga-saham-dengan-bve">c.&nbsp;Uji Korelasi Hubungan antara Variabel Harga Saham dengan BVE</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(FDR<span class="sc">$</span>BVE, FDR<span class="sc">$</span><span class="st">`</span><span class="at">Harga Saham</span><span class="st">`</span>, <span class="at">method =</span> <span class="st">"pearson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  FDR$BVE and FDR$`Harga Saham`
t = 9.3529, df = 810, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.2487431 0.3729883
sample estimates:
   cor 
0.3122 </code></pre>
</div>
</div>
<p>Berdasarkan uji korelasi bungan antara variabel Harga Saham dan BVE menunjukkan bahwa terdapat hubungan positif yang signifikan antara BVE dan Harga Saham. Meskipun signifikan, nilai korelasi (0.3122) menunjukkan hubungan yang rendah antara kedua variabel.</p>
</section>
</section>
</section>
<section id="pemodelan-menggunakan-regresi-liniear-berganda" class="level2">
<h2 class="anchored" data-anchor-id="pemodelan-menggunakan-regresi-liniear-berganda">5. Pemodelan menggunakan Regresi Liniear Berganda</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>regresi <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">Harga Saham</span><span class="st">`</span> <span class="sc">~</span> Profit <span class="sc">+</span> EPS <span class="sc">+</span> BVE, <span class="at">data =</span> FDR)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regresi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = `Harga Saham` ~ Profit + EPS + BVE, data = FDR)

Residuals:
   Min     1Q Median     3Q    Max 
-21391   -967   -813   -249  45582 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 1056.87192  128.88010   8.200 9.39e-16 ***
Profit         0.63348    0.05880  10.774  &lt; 2e-16 ***
EPS            1.25127    0.11374  11.001  &lt; 2e-16 ***
BVE           -0.01087    0.01371  -0.793    0.428    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3587 on 808 degrees of freedom
Multiple R-squared:  0.327, Adjusted R-squared:  0.3245 
F-statistic: 130.9 on 3 and 808 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Dari hasil regresi linear berganda yang telah dilakukan, dapat disimpulkan bahwa variabel yang berpengaruh signifikan terhadap Harga Saham (Y) adalah variabel Profit (X1) dan EPS (X2). Hal ini ditunjukkan pada nilai p-value dari variabel EPS dan BVE yang menunjukkan kurang dari 0.05. Sedangkan, p-value dari variabel BVE (X3) lebih dari 0.05 yaitu sebesar 0.428 yang artinya tidak berpengaruh signifikan terhadap variabel Harga Saham (Y). Variabel X1, X2, dan X3 berpengaruh terhadap variabel Y sebesar 32.7%.</p>
<p>Model Regresi:</p>
<p>Y = 1056.87 + 0.63 X1 + 1.25 X2 - 0.01 X3</p>
<p>Harga Saham = 1056.87 + 0.63 x Profit + 1.25 x EPS - 0.01 x BVE</p>
</section>
<section id="melakukan-uji-normalitas-data" class="level2">
<h2 class="anchored" data-anchor-id="melakukan-uji-normalitas-data">6. Melakukan Uji Normalitas Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(regresi<span class="sc">$</span>residuals, <span class="fu">ecdf</span>(regresi<span class="sc">$</span>residuals))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in ks.test.default(regresi$residuals, ecdf(regresi$residuals)): ties
should not be present for the Kolmogorov-Smirnov test</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Asymptotic one-sample Kolmogorov-Smirnov test

data:  regresi$residuals
D = 0.0036946, p-value = 1
alternative hypothesis: two-sided</code></pre>
</div>
</div>
<p>Berdasarkan uji normalitas data menunjukkan bahwa data berdistribusi normal karena nilai p-value lebih dari 0.05 yaitu sebesar 1. Dikarenakan nilai p-value yang tinggi, maka kita tidak memiliki bukti yang cukup untuk menolak hipotesis nol. Oleh karena itu, distribusi residu dari model regresi tidak berbeda secara signifikan dari distribusi kumulatif empiris yang diharapkan.</p>
</section>
<section id="melakukan-uji-autokorelasi" class="level2">
<h2 class="anchored" data-anchor-id="melakukan-uji-autokorelasi">7. Melakukan Uji Autokorelasi</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dwtest</span>(regresi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  regresi
DW = 2.0802, p-value = 0.8731
alternative hypothesis: true autocorrelation is greater than 0</code></pre>
</div>
</div>
<p>Uji Dorbin-Watson untuk autokorelasi pada model regresi menunjukkan bahwa data telah memenuhi syarat autokorelasi karena p-value lebih dari 0.05 yaitu sebesar 0.87. Nilai DW sebesar 2.08 yakni berada di antara 0 dan 4. Nilai DW mendekati 2, yang menunjukkan bahwa ada sedikit indikasi autocorrelation pada residual. Nilai yang mendekati 0 mengindikasikan autokorelasi positif, sementara nilai yang mendekati 4 mengindikasikan autokorelasi negatif.</p>
</section>
<section id="melakukan-uji-homogenitas" class="level2">
<h2 class="anchored" data-anchor-id="melakukan-uji-homogenitas">8. Melakukan Uji Homogenitas</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(regresi, <span class="at">studentize =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Breusch-Pagan test

data:  regresi
BP = 4641.3, df = 3, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Berdasarkan uji homogenitas menunjukkan bahwa p-value sangat kecil yaitu kurang dari 0.05 yang artinya adanya bukti statistik yang cukup untuk menolak hipotesis nol, yang berarti kita memiliki indikasi bahwa ada heteroskedastisitas dalam kesalahan model.</p>
</section>
<section id="melakukan-uji-multikolinearitas" class="level2">
<h2 class="anchored" data-anchor-id="melakukan-uji-multikolinearitas">9. Melakukan Uji Multikolinearitas</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(regresi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Profit      EPS      BVE 
1.023603 2.074840 2.041180 </code></pre>
</div>
</div>
<p>Secara umum, hasil VIF menunjukkan bahwa tidak ada masalah multicollinearity yang signifikan antara variabel dalam model regresi. Meskipun terdapat beberapa indikasi multicollinearity pada variabel EPS dan BVE, nilainya masih di bawah ambang batas yang umumnya diterima.</p>
</section>
<section id="interpretasi-hasil-analisis-terhadap-model" class="level2">
<h2 class="anchored" data-anchor-id="interpretasi-hasil-analisis-terhadap-model">10. Interpretasi Hasil Analisis terhadap Model</h2>
<section id="berapa-persen-kemampuan-prediksi-model-regresi-yang-digunakan" class="level3">
<h3 class="anchored" data-anchor-id="berapa-persen-kemampuan-prediksi-model-regresi-yang-digunakan">Berapa persen kemampuan prediksi model regresi yang digunakan?</h3>
<p>Dengan melihat nilai Multiple R-squared dalam melakukan uji regresi linear berganda menunjukkan bahwa seberapa baik variabel independen secara bersamaan dapat menjelaskan variasi dalam variabel dependen. Sehingga Multiple R-squared sebesar 32.7% dari variasi variabel dependen (Harga Saham) dapat dijelaskan oleh model regresi di atas.</p>
</section>
<section id="variabel-apa-saja-yang-memiliki-nilai-prediksi-paling-besar-terhadap-harga-saham" class="level3">
<h3 class="anchored" data-anchor-id="variabel-apa-saja-yang-memiliki-nilai-prediksi-paling-besar-terhadap-harga-saham">Variabel apa saja yang memiliki nilai prediksi paling besar terhadap Harga Saham?</h3>
<p>Dengan melihat hasil uji regresi linear berganda menunjukkan bahwa interpretasi koefisien Profit sebesar 0.63, EPS sebesar 1.25, dan BVE sebesar -0.01.</p>
<p>Koefisien Profit sebesar 0.63 artinya dengan tetap mempertahankan nilai variabel EPS dan BVE, setiap peningkatan satu unit dalam Profit dikaitkan dengan peningkatan sekitar 0.63 unit dalam Harga Saham.</p>
<p>Koefisien EPS sebesar 1.25 artinya dengan mempertahankan nilai variabel Profit dan BVE, setiap peningkatan satu unit dalam EPS dikaitkan dengan peningkatan sekitar 1.25 unit dalam Harga Saham.</p>
<p>Koefisien BVE sebesar -0.01 artinya dengan mempertahankan nilai variabel Profit dan EPS, setiap peningkatan satu unit dalam BVE dikaitkan dengan penurunan sekitar 0.01 unit dalam Harga Saham.</p>
<p>Hal ini dapat disimpulkan bahwa variabel yang memiliki nilai prediksi paling besar terhadap variabel Harga Saham adalah variabel EPS (Earning Per Share).</p>
</section>
</section>
<section id="kesimpulan-akhir" class="level2">
<h2 class="anchored" data-anchor-id="kesimpulan-akhir">11. Kesimpulan Akhir</h2>
<p>Model regresi dapat digunakan untuk memprediksi Harga Saham berdasarkan variabel Profit dan EPS karena dua variabel tersebut memiliki hubungan positif yang signifikan dengan variabel Harga Saham.</p>
<p>Korelasi yang signifikan antara variabel EPS dan Harga Saham menunjukkan adanya pengaruh kuat karena di antara tiga variabel independen yang diuji, variabel EPS yang memiliki nilai prediksi paling besar terhadap variabel Harga Saham.</p>
<p>Meskipun model memiliki kelebihan, perlu mempertimbangkan penanganan heteroskedastisitas pada kesalahan model.</p>
<p>Evaluasi lebih lanjut atau penyesuaian model dapat dilakukan untuk meningkatkan keandalan dan ketepatan prediksi.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>